### ISSUE TITLE
Proxy settings in sonar.properties are ignored

### ISSUE THREAD

**Issue by mapeters985** [emerald-squad/sonar-shellcheck-plugin#1]
When attempting to download the shellcheck file, I get this error: java.net.UnknownHostException: shellcheck.storage.googleapis.com. I believe that is because the proxy settings that I have configured in my sonar.properties file are ignored.

**Comment by thomasd-** [comment]
Proxy settings are not supposed to be set in sonar.properties, to set them properly, you need to pass them to the JVM using the environment variable SONAR_SCANNER_OPTS

`export SONAR_SCANNER_OPTS="-Dhttps.proxyHost=<host> -Dhttps.proxyPort=<port>"`
